import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Hero from '../components/Hero'
import Tabs from '../components/Tabs'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect1.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>H2 Heading</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</p>
          </a>

          <a href="#" className={styles.card}>
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect2.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>H2 Heading</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect3.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>H2 Heading</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect4.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>H2 Heading</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.
            </p>
          </a>
        </div>
        <Tabs />
      </main>


    </div>
  )
}
