import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Hero from '../components/Hero'
import Tabs from '../components/Tabs'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero />
        {/*         <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect1.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>Documentation</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect2.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>Learn</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect3.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>Examples</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <div className={styles.cardImageBack}>
              <Image src="/home/cards/rect4.png" objectFit='contain' width={36} height={36} />
            </div>
            <h2>Deploy</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
        <Tabs />
      </main>


    </div>
  )
}
